# Site settings
title: SimBioSys Lab
description: Systems and biology at Emory University
keywords:
  - Computer Systems
  - Networked Systems
  - Memory Caches
  - Machine Learning
  - Computational Epidemiology
  - Data Science
  - Neural Networks
  - Neuroscience
  - Information Retrieval
baseurl: ""
url: "http://simbiosyslab.github.io"
github_username: SimBioSysLab

# Build settings
markdown: kramdown
permalink: /:title

sections:
  - News
  - Home
  - People
  - Projects
  - Publications
  - Partners
  - Prospective Student
